spring:
  application:
    name: item-server
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lidong-9527s/
          search-paths: 
          - sp02-itemservice 
    
#server:
#  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
---
spring:
  profiles: item1
  
server:
  port: 8001
---
spring:
  profiles: item2

server:
  port: 8002